name: My first Github Action
on: [push]
jobs: 
  build-app:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - name: Intall Node Modules
        run: npm install
      - name: Buld the project
        run: npm run build
      - name: Deploy project
        env: 
          VERCEL_ORG_ID: pcsVFUtsDKcAE6PYUVZUcloa
          VERCEL_PROJECT_ID: prj_rH24v5C4545IcDcMtYsxu83FslQw
        run: npm run deploy
      - name: Setup Finished
        run: echo "Finished"